name: Sync Registry
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Sync Registry
      uses: onichandame/docker-registry-sync-action@master
      with:
        source_repository: docker.io/luolongfei/freenom:latest
        source_username: ${{ secrets.DOCKERHUB_USERNAME }}
        source_password: ${{ secrets.DOCKERHUB_PASSWORD }}
        target_repository: docker.io/rouroux/freenom-automatic-renewal:latest
        target_username: ${{ secrets.DOCKERHUB_USERNAME }}
        target_password: ${{ secrets.DOCKERHUB_PASSWORD }}